import type { Metadata } from "next";
import { Pathway_Extreme } from "next/font/google";
import { Header } from "@/components/Header";
import "./globals.css";

const pathway_extreme = Pathway_Extreme({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "My World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pathway_extreme.className} antialiased overflow-x-hidden`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
